### ISSUE TITLE
Running npm run stage:save clears out work

### ISSUE THREAD

**Issue by micahrcorn** [PacktPublishing/React-Application-Architecture-for-Production#3]
I am following along the book. After running the stage switch command and choosing to work in the chapter 3 start and coding in chapter three start, when I run `npm run stage:save` and confirm the changes, all progress is being wiped out in the chapter three start dir. I am never seeing the changes in the updated `src`. Where am I screwing up in the workflow?

**Comment by alan2207** [comment]
Hey @micahrcorn , that's very strange. Anything you modify in the `src` should get copied to `code-stages/chapter-03-start` upon saving. Are you saying that the content from `code-stages/chapter-03-start` gets deleted, and remains empty?

Can you provide more info, such as the steps you made, the outputs you received in the console, and what OS and Node version you are using?

**Comment by micahrcorn** [comment]
Aight, so I run ` npm run stage:switch` and choose `chapter-03-start` and `npm run dev` to spin it up. I read the README and it states _The files of the selected chapter will be copied to the main directory. You can now start working on the code._

Currently it is unclear in my ide `Webstorm` `node 19..6.1``mac m2 ventura` what is the main directory I am supposed to be working in. I assumed that I would be working inside of the `chapter-03-start/src` dir, and those saves would show up in the top level ignored dir `src`. I could be totally off in assuming this.  When making changes in the working dir `chapter-03-start/src` and then running `npm run stage:save` I wasn't seeing any change in the top level `src`. 

<div>
<img width="350" src="https://user-images.githubusercontent.com/3950139/222306818-bc7ef9a6-7fb5-4d1a-ad29-21eef604c8a7.png" />
</div>

**Comment by alan2207** [comment]
Ok, here is how it works:

To make it simpler to maintain dependencies and do a single "npm install" for all the chapters, we have the `code-stages` folder, which keeps code versions of each chapter since each chapter needs some preparations.

When you execute `npm run stage:switch` and choose a version, that version gets copied into the main directory which is the root of the whole project. Notice how each chapter has its own `src`. Well, that gets copied into the root and you start working with it.

To avoid messing up the progress of each chapter, and to keep track of the changes easier, the `src` folder is git ignored. But since some people might want to save their current progress, we have the `stage:save` command which will take what's in the main directory and copy in the `code-stages` version. For example, if you chose to work on `chapter-03-start`, when you run `stage:save` - the `src` folder will update what's in `code-stages/chapter-03-start`, and those changes will be tracked by Git.

**Comment by micahrcorn** [comment]
Right on! I see the ide is warning me that I am editing an ignored file, but it actually isn't. This is a bit confusing but thanks for explaining. Loving what I see so far in the material! Good Job.

**Comment by alan2207** [comment]
Thanks, happy you hear you love the content :)

Btw, if you really want to track the `src` folder, you can do that by removing or commenting out line 50 in `.gitignore`.
